<template><div><h2 id="上传包-如何上传自己的npm包-npm上传-csdn博客" tabindex="-1"><a class="header-anchor" href="#上传包-如何上传自己的npm包-npm上传-csdn博客"><span>上传包 <a href="https://blog.csdn.net/Her_smile/article/details/80519597" target="_blank" rel="noopener noreferrer">如何上传自己的npm包_npm上传-CSDN博客</a></span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> login</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publish</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  //上传</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> unpublish</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --force</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">  //撤销上传</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="淘宝镜像-切换至淘宝镜像" tabindex="-1"><a class="header-anchor" href="#淘宝镜像-切换至淘宝镜像"><span>淘宝镜像  切换至淘宝镜像</span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">#最新地址 淘宝 NPM 镜像站喊你切换新域名啦!</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> config</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> set</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> registry</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> https://registry.npmmirror.com</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="恢复官方镜像源" tabindex="-1"><a class="header-anchor" href="#恢复官方镜像源"><span>恢复官方镜像源</span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> config</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> set</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> registry</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> https://registry.npmjs.org</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


