<template><div><p>本文档详细介绍了如何配置和使用SSH密钥，以安全地连接到Git仓库进行远程操作。步骤包括设置Git用户名和邮箱，生成RSA秘钥，设置密钥名称，设置私钥密码，将私钥添加到本地ssh-agent，开启远程登录功能，并验证SSH连接。此过程对于频繁的Git推送和拉取操作至关重要，确保了身份验证的安全性。</p>
<p>1.配置好git的名字和邮箱
2.生成秘钥</p>
<div class="language-csharp line-numbers-mode" data-highlighter="shiki" data-ext="csharp" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-csharp"><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ssh</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">-</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">keygen</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> -</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">t</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> rsa</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> -</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">C</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">your email</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>3.设置秘钥名字 放在~/.s<a href="https://so.csdn.net/so/search?q=sh%E6%96%87%E4%BB%B6&amp;spm=1001.2101.3001.7020" target="_blank" rel="noopener noreferrer">sh文件</a>夹</p>
<div class="language-cobol line-numbers-mode" data-highlighter="shiki" data-ext="cobol" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-cobol"><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">Enter</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> file</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> in</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> which </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">to</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> save the </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">key</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Users</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.ssh</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">id_rsa): </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Users</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.ssh</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">id_rsa</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>4.设置私钥密码</p>
<div class="language-cobol line-numbers-mode" data-highlighter="shiki" data-ext="cobol" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-cobol"><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">Enter</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> passphrase (empty </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">for</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> no</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> passphrase):  </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">123456</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Your </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">identification</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> has been saved </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">in</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> id_rsa. </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">//</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 私钥</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Your </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">public</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> key</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> has been saved </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">in</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> id_rsa.pub.  </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">//</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">公钥</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">The </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">key</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> fingerprint is:</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">SHA256:IL6L2NjBQDAAuYfD6NzTbR8VIc</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">fJl1coDUhzL3LYP8 </span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">The </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">key</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">s randomart image is:</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+---</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">[RSA 2048]</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">----+</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|B.      . </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">o.</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">o.|</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|o.        </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.o</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.o.|</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|o</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">  . .    oo  .o|</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">*</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">... . .  .</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> +</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> .|</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">o. o . S .. </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">*</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> =</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> o o o .    </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">*</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">  |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|  o o . . .    . |</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">| </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> o .  .      E|</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">|o </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> .            |   </span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">+----</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">[SHA256]</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">-----+</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">  //</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> 创建成功</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>5.添加私钥到本地电脑上</p>
<div class="language-cobol line-numbers-mode" data-highlighter="shiki" data-ext="cobol" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-cobol"><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">cd</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> /</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Users</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.ssh</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">id_rsa </span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ssh-add id_rsa</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>6.输入密码</p>
<div class="language-cobol line-numbers-mode" data-highlighter="shiki" data-ext="cobol" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-cobol"><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">Enter</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> passphrase </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">for</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> id_rsa：</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">123456</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Identity added: id_rsa  </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">//</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">添加成功</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><ol start="7">
<li>开启<a href="https://so.csdn.net/so/search?q=%E8%BF%9C%E7%A8%8B%E7%99%BB%E5%BD%95&amp;spm=1001.2101.3001.7020" target="_blank" rel="noopener noreferrer">远程登录</a>功能，方法：设置——共享——勾选远程登录</li>
<li>与网站进行验证，记录ssh</li>
</ol>
<div class="language-typescript line-numbers-mode" data-highlighter="shiki" data-ext="typescript" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code class="language-typescript"><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ssh</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> -</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">T</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> git</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">@</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">gitee</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">com</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> 回车</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">Are</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> you</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> sure</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> you</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> want</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> to</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> continue</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> connecting</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">yes</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">no</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">/</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">fingerprint</span><span style="--shiki-light:#999999;--shiki-dark:#666666">])</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> yes</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


